# Generated by Django 4.1.4 on 2023-01-10 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_profile_delete_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='liked',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
